apiVersion: v1
kind: Pod
metadata:
  name: my-app
  namespace: vault
  annotations:
    vault.hashicorp.com/tls-skip-verify: "true" # Correct indentation
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "vault-role"
    vault.hashicorp.com/agent-inject-secret-app.env: "kv-v2/vault-demo/mysecret" # Ensure this path is correct
spec:
  serviceAccountName: vault-sa
  containers:
    - name: my-app
      image: mahi2029/golang-repo:go-docker-app2
      ports:
        - containerPort: 9090
      env:
        - name: VAULT_SECRET_PATH
          value: "/vault/secrets/app.env"
